use std::path::PathBuf;

use flexplore::config::{ColorPalette, NodeConfig};
use flexplore::render::{RenderJob, render_to_images};

/// Scan testdata/*/input.json and render each case with Bevy.
/// This reads the canonical fixtures generated by snapshot tests,
/// so the Bevy renders always match the HTML/Tailwind/Flutter outputs.
fn load_jobs(testdata_dir: &PathBuf, filter: &[String]) -> Vec<RenderJob> {
    let mut jobs = Vec::new();

    let mut entries: Vec<_> = std::fs::read_dir(testdata_dir)
        .expect("cannot read testdata directory")
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().map(|t| t.is_dir()).unwrap_or(false))
        .collect();
    entries.sort_by_key(|e| e.file_name());

    for entry in entries {
        let name = entry.file_name().to_string_lossy().into_owned();

        if !filter.is_empty() && !filter.iter().any(|f| f == &name) {
            continue;
        }

        let input_path = entry.path().join("input.json");
        if !input_path.exists() {
            continue;
        }

        let json = std::fs::read_to_string(&input_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", input_path.display()));
        let node: NodeConfig = serde_json::from_str(&json)
            .unwrap_or_else(|e| panic!("failed to parse {}: {e}", input_path.display()));

        // Infer palette from directory name; default to Pastel1
        let palette = if name.contains("dark2") {
            ColorPalette::Dark2
        } else {
            ColorPalette::Pastel1
        };

        jobs.push(RenderJob { name, node, palette });
    }

    jobs
}

fn main() {
    let args: Vec<String> = std::env::args().collect();
    let filter: Vec<String> = args[1..].to_vec();
    let testdata_dir = PathBuf::from("testdata");

    let jobs = load_jobs(&testdata_dir, &filter);
    render_to_images(jobs, testdata_dir);
}
